global:
  scrape_interval: 15s
rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'flask-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['web:5000']   # نام سرویس اپ در compose
